import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import GlobalSearchBar from '@/components/GlobalSearchBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "サウナブログ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 p-4 text-white flex justify-between items-center">
          <ul className="flex space-x-4">
            <li><Link href="/">ホーム</Link></li>
            <li><Link href="/sauna">サウナとは</Link></li>
            <li><Link href="/new-post">新規作成</Link></li>
          </ul>
          <GlobalSearchBar />
        </nav>
        {children}
      </body>
    </html>
  );
}