import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "サウナブログ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-900 p-4 text-white flex justify-between items-center shadow-lg">
          <ul className="flex space-x-4">
            <li><Link href="/" className="hover:text-yellow-400 transition-colors duration-200">ホーム</Link></li>
            <li><Link href="/sauna" className="hover:text-yellow-400 transition-colors duration-200">サウナとは</Link></li>
            <li><Link href="/new-post" className="hover:text-yellow-400 transition-colors duration-200">新規作成</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}